# This file contains parameter for several test controllers, which will be uploaded to the ros parameter server via
# the roslaunch file
motor0:
  joint_name: motor0
  type: roboy_controller/PositionController

motor1:
  joint_name: motor1
  type: roboy_controller/ForceController

motor2:
  joint_name: motor2
  type: roboy_controller/PositionController

motor3:
  joint_name: motor3
  type: roboy_controller/PositionController

motor4:
  joint_name: motor4
  type: roboy_controller/PositionController

motor5:
  joint_name: motor5
  type: roboy_controller/PositionController

motor6:
  joint_name: motor6
  type: roboy_controller/PositionController

motor7:
  joint_name: motor7
  type: roboy_controller/PositionController

motor8:
  joint_name: motor8
  type: roboy_controller/PositionController

motor9:
  joint_name: motor9
  type: roboy_controller/PositionController

motor10:
  joint_name: motor10
  type: roboy_controller/PositionController

motor11:
  joint_name: motor11
  type: roboy_controller/PositionController

motor12:
  joint_name: motor12
  type: roboy_controller/PositionController

motor13:
  joint_name: motor13
  type: roboy_controller/PositionController

motor14:
  joint_name: motor14
  type: roboy_controller/PositionController

motor15:
  joint_name: motor15
  type: roboy_controller/PositionController

motor16:
  joint_name: motor16
  type: roboy_controller/PositionController

motor17:
  joint_name: motor17
  type: roboy_controller/PositionController

motor18:
  joint_name: motor18
  type: roboy_controller/PositionController

motor19:
  joint_name: motor19
  type: roboy_controller/PositionController

motor20:
  joint_name: motor20
  type: roboy_controller/PositionController

motor21:
  joint_name: motor21
  type: roboy_controller/PositionController

motor22:
  joint_name: motor22
  type: roboy_controller/PositionController

motor23:
  joint_name: motor23
  type: roboy_controller/PositionController
