# This file contains parameter for several test controllers, which will be uploaded to the ros parameter server via
# the roslaunch file
motor0:
  joint_name: motor0
  type: roboy_controller/singleJoint_controller

motor1:
  joint_name: motor1
  type: roboy_controller/singleJoint_controller

motor2:
  joint_name: motor2
  type: roboy_controller/singleJoint_controller

motor3:
  joint_name: motor3
  type: roboy_controller/singleJoint_controller

motor4:
  joint_name: motor4
  type: roboy_controller/singleJoint_controller

motor5:
  joint_name: motor5
  type: roboy_controller/singleJoint_controller

motor6:
  joint_name: motor6
  type: roboy_controller/singleJoint_controller

motor7:
  joint_name: motor7
  type: roboy_controller/singleJoint_controller

motor8:
  joint_name: motor8
  type: roboy_controller/singleJoint_controller

motor9:
  joint_name: motor9
  type: roboy_controller/singleJoint_controller

motor10:
  joint_name: motor10
  type: roboy_controller/singleJoint_controller

motor11:
  joint_name: motor11
  type: roboy_controller/singleJoint_controller

motor12:
  joint_name: motor12
  type: roboy_controller/singleJoint_controller

motor13:
  joint_name: motor13
  type: roboy_controller/singleJoint_controller

motor14:
  joint_name: motor14
  type: roboy_controller/singleJoint_controller

motor15:
  joint_name: motor15
  type: roboy_controller/singleJoint_controller

motor16:
  joint_name: motor16
  type: roboy_controller/singleJoint_controller

motor17:
  joint_name: motor17
  type: roboy_controller/singleJoint_controller

motor18:
  joint_name: motor18
  type: roboy_controller/singleJoint_controller

motor19:
  joint_name: motor19
  type: roboy_controller/singleJoint_controller

motor20:
  joint_name: motor20
  type: roboy_controller/singleJoint_controller

motor21:
  joint_name: motor21
  type: roboy_controller/singleJoint_controller

motor22:
  joint_name: motor22
  type: roboy_controller/singleJoint_controller

motor23:
  joint_name: motor23
  type: roboy_controller/singleJoint_controller
